create table if not exists public.budgets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null,
  amount numeric(12, 2) not null check (amount > 0),
  month smallint not null check (month between 1 and 12),
  year smallint not null check (year between 2000 and 2200),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, category, year, month)
);

create index if not exists budgets_user_period_idx
  on public.budgets (user_id, year, month);

create index if not exists transactions_user_date_idx
  on public.transactions (user_id, date);

create index if not exists subscriptions_user_idx
  on public.subscriptions (user_id);

create index if not exists custom_categories_user_idx
  on public.custom_categories (user_id);

alter table public.transactions
  add column if not exists recurring_source_id text,
  add column if not exists recurring_period date;

create unique index if not exists transactions_recurring_period_key
  on public.transactions (user_id, recurring_source_id, recurring_period);

alter table public.transactions enable row level security;
alter table public.subscriptions enable row level security;
alter table public.custom_categories enable row level security;
alter table public.budgets enable row level security;

drop policy if exists "zaizen_transactions_owner" on public.transactions;
create policy "zaizen_transactions_owner"
  on public.transactions
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "zaizen_subscriptions_owner" on public.subscriptions;
create policy "zaizen_subscriptions_owner"
  on public.subscriptions
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "zaizen_custom_categories_owner" on public.custom_categories;
create policy "zaizen_custom_categories_owner"
  on public.custom_categories
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "zaizen_budgets_owner" on public.budgets;
create policy "zaizen_budgets_owner"
  on public.budgets
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
