begin;

create table if not exists public.recurring_budgets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null,
  amount numeric(12, 2) not null check (amount > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, category)
);

create index if not exists recurring_budgets_user_idx
  on public.recurring_budgets (user_id, active);

alter table public.recurring_budgets enable row level security;

drop policy if exists "zaizen_recurring_budgets_owner" on public.recurring_budgets;
create policy "zaizen_recurring_budgets_owner"
  on public.recurring_budgets
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

revoke all privileges on table public.recurring_budgets from public, anon;
grant select, insert, update, delete on table public.recurring_budgets to authenticated;

-- Keep account deletion complete when recurring budgets are enabled.
create or replace function public.delete_own_account()
returns void
language plpgsql
security definer
set search_path = ''
as $function$
declare
  requesting_user uuid := auth.uid();
  last_login timestamptz;
begin
  if requesting_user is null then
    raise exception 'Authentication required';
  end if;

  select users.last_sign_in_at
    into last_login
  from auth.users as users
  where users.id = requesting_user;

  if last_login is null or last_login < pg_catalog.now() - interval '15 minutes' then
    raise exception 'Recent authentication required';
  end if;

  delete from public.savings_contributions where user_id = requesting_user;
  delete from public.savings_goals where user_id = requesting_user;
  delete from public.categorization_rules where user_id = requesting_user;
  delete from public.recurring_budgets where user_id = requesting_user;
  delete from public.budgets where user_id = requesting_user;
  delete from public.transactions where user_id = requesting_user;
  delete from public.subscriptions where user_id = requesting_user;
  delete from public.custom_categories where user_id = requesting_user;
  delete from auth.users where id = requesting_user;
end;
$function$;

revoke all on function public.delete_own_account() from public, anon;
grant execute on function public.delete_own_account() to authenticated;

commit;
