create table if not exists public.savings_goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  target_amount numeric(12, 2) not null check (target_amount > 0),
  target_date date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.savings_contributions (
  id bigint generated by default as identity primary key,
  goal_id bigint not null references public.savings_goals(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount numeric(12, 2) not null check (amount > 0),
  contribution_date date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists savings_goals_user_idx
  on public.savings_goals (user_id);

create index if not exists savings_contributions_goal_idx
  on public.savings_contributions (goal_id);

alter table public.savings_goals enable row level security;
alter table public.savings_contributions enable row level security;

drop policy if exists "zaizen_savings_goals_owner" on public.savings_goals;
create policy "zaizen_savings_goals_owner"
  on public.savings_goals
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "zaizen_savings_contributions_owner" on public.savings_contributions;
create policy "zaizen_savings_contributions_owner"
  on public.savings_contributions
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
