create table if not exists public.categorization_rules (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  pattern text not null,
  category text not null,
  transaction_type text not null check (transaction_type in ('expense', 'income')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, pattern, transaction_type)
);

create index if not exists categorization_rules_user_idx
  on public.categorization_rules (user_id);

alter table public.categorization_rules enable row level security;

drop policy if exists "zaizen_categorization_rules_owner" on public.categorization_rules;
create policy "zaizen_categorization_rules_owner"
  on public.categorization_rules
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
